/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import ferramentas.Deposito;
import javax.swing.JOptionPane;

/**
 *
 * @author anderson.collin
 */
public class TelaDeposito extends javax.swing.JFrame {

    private int tenant_id;
    private double saldo;
    private double limite;
    private double limite_usado;

    /**
     * Creates new form TelaDeposito
     */
    public TelaDeposito() {
        initComponents();
    }

    public int getTenant_id() {
        return tenant_id;
    }

    public void setTenant_id(int tenant_id) {
        this.tenant_id = tenant_id;
    }

    public double getSaldo() {
        return saldo;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public double getLimite() {
        return limite;
    }

    public void setLimite(double limite) {
        this.limite = limite;
    }

    public double getLimite_usado() {
        return limite_usado;
    }

    public void setLimite_usado(double limite_usado) {
        this.limite_usado = limite_usado;
    }
    
    private boolean deposito(double valor) {
        Deposito d = new Deposito(getSaldo(), getLimite(), getLimite_usado(), getTenant_id());
       return d.doDeposito(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTtitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCvalor = new javax.swing.JComboBox<>();
        jBoutroValor = new javax.swing.JButton();
        jToutroValor = new javax.swing.JTextField();
        jBconfirma = new javax.swing.JButton();
        jBcancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Deposito");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTtitulo.setEditable(false);
        jTtitulo.setText("DEPOSITO CEDULAS");
        jTtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtituloActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor: R$");

        jCvalor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "50", "100", "150", "200" }));
        jCvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCvalorActionPerformed(evt);
            }
        });

        jBoutroValor.setText("Outro Valor");
        jBoutroValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoutroValorActionPerformed(evt);
            }
        });

        jToutroValor.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTtitulo)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jBoutroValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToutroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoutroValor)
                    .addComponent(jToutroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jBconfirma.setText("Confirma");
        jBconfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmaActionPerformed(evt);
            }
        });

        jBcancela.setText("Cancela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBcancela)
                        .addGap(18, 18, 18)
                        .addComponent(jBconfirma)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBconfirma)
                    .addComponent(jBcancela))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtituloActionPerformed

    private void jCvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCvalorActionPerformed
        // TODO add your handling code here:

        if (jCvalor.getSelectedItem().toString().equals("Outro Valor")) {
            jToutroValor.setEnabled(true);
        }
    }//GEN-LAST:event_jCvalorActionPerformed

    private void jBoutroValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoutroValorActionPerformed
        // TODO add your handling code here:
        jCvalor.setEnabled(false);
        jToutroValor.setEditable(true);
    }//GEN-LAST:event_jBoutroValorActionPerformed

    private void jBconfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmaActionPerformed
        // TODO add your handling code here:
        if (jCvalor.isEnabled() && jToutroValor.getText().isEmpty()) {
            double temp;
            temp = Double.parseDouble(jCvalor.getSelectedItem().toString());
            if (deposito(temp)) {
                JOptionPane.showMessageDialog(rootPane, "Deposito realizado com sucesso");
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deposito não foi realizado");
            }
        } else {
            double temp;
            temp = Double.parseDouble(jToutroValor.getText());
            if (deposito(temp)) {
                JOptionPane.showMessageDialog(rootPane, "Deposito realizado com sucesso");
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deposito não foi realizado");
            }
        }
    }//GEN-LAST:event_jBconfirmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancela;
    private javax.swing.JButton jBconfirma;
    private javax.swing.JButton jBoutroValor;
    private javax.swing.JComboBox<String> jCvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jToutroValor;
    private javax.swing.JTextField jTtitulo;
    // End of variables declaration//GEN-END:variables
}
